# Raspberry Pi 5 cross-compilation toolchain for CMake.
#
# Usage example:
#   cmake -S . -B build-rpi -DCMAKE_TOOLCHAIN_FILE=toolchain-rpi.cmake \
#     -DRPI_TOOLCHAIN_PREFIX=aarch64-linux-gnu \
#     -DRPI_SYSROOT=/path/to/raspberry-pi-sysroot

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED RPI_TOOLCHAIN_PREFIX)
    set(RPI_TOOLCHAIN_PREFIX aarch64-linux-gnu)
endif()

if(NOT DEFINED RPI_TOOLCHAIN_BIN_DIR OR RPI_TOOLCHAIN_BIN_DIR STREQUAL "")
    set(RPI_TOOLCHAIN_BIN_DIR "")
endif()

find_program(RPI_C_COMPILER
    NAMES ${RPI_TOOLCHAIN_PREFIX}-gcc
    HINTS ${RPI_TOOLCHAIN_BIN_DIR}
    PATHS /usr/bin /usr/local/bin
    NO_DEFAULT_PATH)

find_program(RPI_CXX_COMPILER
    NAMES ${RPI_TOOLCHAIN_PREFIX}-g++
    HINTS ${RPI_TOOLCHAIN_BIN_DIR}
    PATHS /usr/bin /usr/local/bin
    NO_DEFAULT_PATH)

find_program(RPI_ASM_COMPILER
    NAMES ${RPI_TOOLCHAIN_PREFIX}-gcc
    HINTS ${RPI_TOOLCHAIN_BIN_DIR}
    PATHS /usr/bin /usr/local/bin
    NO_DEFAULT_PATH)

if(NOT RPI_C_COMPILER)
    message(FATAL_ERROR "Could not find ${RPI_TOOLCHAIN_PREFIX}-gcc. Install the aarch64 cross toolchain or set RPI_TOOLCHAIN_BIN_DIR.")
endif()

if(NOT RPI_CXX_COMPILER)
    message(FATAL_ERROR "Could not find ${RPI_TOOLCHAIN_PREFIX}-g++. Install the aarch64 g++ cross package or set RPI_TOOLCHAIN_BIN_DIR.")
endif()

set(CMAKE_C_COMPILER ${RPI_C_COMPILER})
set(CMAKE_CXX_COMPILER ${RPI_CXX_COMPILER})
set(CMAKE_ASM_COMPILER ${RPI_ASM_COMPILER})

if(DEFINED RPI_SYSROOT AND NOT RPI_SYSROOT STREQUAL "")
    set(CMAKE_SYSROOT ${RPI_SYSROOT})
    set(CMAKE_FIND_ROOT_PATH ${RPI_SYSROOT})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)