@startuml overview

class RPI
class Base {
    left_encoder
    right_encoder
    left_speed
    right_speed
    left_set_speed
    right_set_speed
    **wall_tof
    bump_left
    bump_right
    **wall_left
    **wall_mid
    **wall_right
    cliff_left
    cliff_front_left
    cliff_front_right
    cliff_right
    **lidar_bump_a
    **lidar_bump_b
    dc_plug
    dust_box
    mop_l
}
class Maincontroller
class Head {
    Yaw rotate L/R
    Pitch rotate B/F
}
class Arm {
    Joint 1 L/R
    Joint 2 BCK/FWD
    Joint 3 BCK/FWD
    Joint 4 BCK/FWD
    Joint 5 L/R
    Joint 6 L/R
}
class Eyes_FW {
    **plaatjes van ogen
}

RPI -- Maincontroller : USB (serial, ttyACM0) >
RPI -- GripperCam : USB (webcam, video0)
RPI -- HeadCam :  USB (webcam, video2)
RPI -- HeadSpeaker : USB (geluidskaart RPI, kanaal 1)
RPI -- HeadMic : USB (standaard microfoon)

Maincontroller -- Base :  UART (RX/TX) >
Maincontroller -- Temperature : I2C (0x4B, p3t1755dpz)
Maincontroller -- ToF_Left : I2C (0x2B, VL53L7CX) >
Maincontroller -- ToF_Right : I2C (0x2A, VL53L7CX) >
Maincontroller -- Headcontroller: I2C (0x5B) >
Maincontroller -- Eyescontroller: I2C (0x5A) >
Maincontroller -- Armcontroller: I2C (0x5C) >
Armcontroller -- Arm : ? (servo 6-DoF, Cobot280) >
Armcontroller -- Gripper :  onewire (L7805CV via 74lvc1g125gw/74lvc1g126gw 3-state bus driver) >
Headcontroller -- Head : onewire (Dynamixel servo 2-DoF 74lvc1g125gw/74lvc1g126gw 3-state bus driver) >
Eyescontroller -- "2" Eyes_FW : ? >
Eyescontroller -- Mouth : Audio_R (Graphic Equalizer MSGEQ7) >

@enduml
